//
// Created by marcel on 24.07.23.
//

#ifndef FICTION_BDL_INPUT_ITERATOR_HPP
#define FICTION_BDL_INPUT_ITERATOR_HPP

#include "fiction/algorithms/simulation/sidb/detect_bdl_pairs.hpp"
#include "fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp"
#include "fiction/technology/cell_technologies.hpp"
#include "fiction/technology/charge_distribution_surface.hpp"
#include "fiction/traits.hpp"

#include <fiction/technology/sidb_bdl_circuit.hpp>
#include <fiction/types.hpp>

#include <cassert>
#include <cstdint>
#include <iterator>
#include <vector>

namespace fiction
{

/**
 * Parameters for the BDL input iterator.
 */
struct bdl_input_iterator_params
{
    /**
     * This enum defines how BDL inputs are manipulated within the algorithm.
     * According to existing literature, there are two main approaches for handling BDL inputs:
     *
     * 1. Distance Encoding, in which an input of `1` is generated by placing a perturber closer to the target, whereas
     * a `0` is produced by positioning the perturber farther away (as described in
     * https://dl.acm.org/doi/10.1145/3489517.3530525).
     * 2. Absence Encoding, in which a perturber is used to set the input to `1`, while the absence of a perturber
     * represents a `0` (as described in https://ieeexplore.ieee.org/abstract/document/8963859).
     */
    enum class input_bdl_configuration : uint8_t
    {
        /**
         * An input of `1` is generated by placing a perturber closer to the BDL wire, whereas a `0` is produced
         * by positioning the perturber farther away (as described in https://dl.acm.org/doi/10.1145/3489517.3530525).
         */
        PERTURBER_DISTANCE_ENCODED,
        /**
         * A perturber is used to set the input to `1`, while the absence of a perturber represents a `0`
         * (as described in https://ieeexplore.ieee.org/abstract/document/8963859).
         */
        PERTURBER_ABSENCE_ENCODED
    };
    /**
     * Parameters to detect BDL wires.
     */
    detect_bdl_wires_params bdl_wire_params{};
    /**
     * The `input_bdl_config` member allows selection between different modes for handling input BDLs.
     */
    input_bdl_configuration input_bdl_config{input_bdl_configuration::PERTURBER_DISTANCE_ENCODED};
};

enum class simulate_bdl_wire_logic
{
    COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS,
    DO_NOT_COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS
};

/**
 * Iterator that iterates over all possible input states of a BDL layout. There are \f$2^n\f$ possible input states
 * for an \f$n\f$-input BDL layout, each with a unique input index. The input index is interpreted as a binary number,
 * where the \f$i\f$-th bit represents the input state of the \f$i\f$-th input BDL pair. If the bit is `1`, the lower
 * BDL dot is set and the upper BDL dot removed. If the bit is `0`, the upper BDL dot is removed and the lower BDL dot
 * set. The iterator creates and stores a deep-copy of the given layout. The state enumeration wraps around, i.e., after
 * the last possible input state, the first input state is set again.
 *
 * The iterator satisfies the requirements of `LegacyRandomAccessIterator` and can be used in iterator-based `for`
 * loops.
 *
 * @tparam Lyt SiDB cell-level layout type.
 */
template <
    typename Lyt,
    simulate_bdl_wire_logic sim_bdl_wire_logic = simulate_bdl_wire_logic::DO_NOT_COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS,
    typename GateLyt = hex_even_row_gate_clk_lyt, typename SkeletonGateLibrary = sidb_skeleton_bestagon_mini_library>
class bdl_input_iterator
{
  public:
    /**
     * Standard constructor. It alters the layout to set the first input state, which assigns binary `0` to all input
     * BDL pairs.
     *
     * @param lyt The SiDB BDL layout to iterate over.
     * @param ps Parameters for the BDL input iterator.
     */
    explicit bdl_input_iterator(
        const Lyt& lyt, const bdl_input_iterator_params& ps = bdl_input_iterator_params{},
        const std::optional<std::reference_wrapper<const sidb_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>>>
            bdl_circuit = std::nullopt,
        const std::optional<
            const std::reference_wrapper<const sidb_cell_level_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>>>
                                       bdl_sub_circuit            = std::nullopt,
        const std::optional<uint64_t>& input_index_of_sub_circuit = std::nullopt) noexcept :
            layout{lyt.clone()},
            input_pairs{
                detect_bdl_pairs<Lyt>(lyt, sidb_technology::cell_type::INPUT, ps.bdl_wire_params.bdl_pairs_params)},
            num_inputs{static_cast<uint8_t>(input_pairs.size())},
            input_bdl_wires{detect_bdl_wires<Lyt>(lyt, ps.bdl_wire_params, bdl_wire_selection::INPUT)},
            last_bdl_for_each_wire{determine_last_bdl_for_each_wire()},
            params{ps},
            circuit{bdl_circuit},
            sub_circuit{bdl_sub_circuit},
            sub_circuit_input_index{input_index_of_sub_circuit},
            circuit_with_sub_circuit{circuit.has_value() ?
                                         std::make_optional(make_circuit_with_sub_circuit(*circuit, *sub_circuit)) :
                                         std::nullopt}
    {
        static_assert(is_cell_level_layout_v<Lyt>, "Lyt is not a cell-level layout");
        static_assert(has_sidb_technology_v<Lyt>, "Lyt is not an SiDB layout");

        if constexpr (sim_bdl_wire_logic == simulate_bdl_wire_logic::COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS)
        {
            simulated_bdl_wires.emplace(std::vector<std::optional<charge_distribution_surface<Lyt>>>{});
            simulated_bdl_wires->reserve(num_inputs);
        }

        set_all_inputs();
    }

    /**
     * Constructor with pre-detected input wires and directions. It alters the layout to set the first input state,
     * which assigns binary `0` to all input BDL pairs.
     *
     * @param lyt The SiDB BDL layout to iterate over.
     * @param ps Parameters for the BDL input iterator.
     * @param input_wires Pre-detected input BDL wires.
     */
    explicit bdl_input_iterator(
        const Lyt& lyt, const bdl_input_iterator_params& ps, const std::vector<bdl_wire<Lyt>>& input_wires,
        const std::optional<std::reference_wrapper<const sidb_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>>>
            bdl_circuit = std::nullopt,
        const std::optional<
            std::reference_wrapper<const sidb_cell_level_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>>>
                                       bdl_sub_circuit            = std::nullopt,
        const std::optional<uint64_t>& input_index_of_sub_circuit = std::nullopt) noexcept :
            layout{lyt.clone()},
            input_pairs{
                detect_bdl_pairs<Lyt>(lyt, sidb_technology::cell_type::INPUT, ps.bdl_wire_params.bdl_pairs_params)},
            num_inputs{static_cast<uint8_t>(input_pairs.size())},
            input_bdl_wires{input_wires},
            last_bdl_for_each_wire{determine_last_bdl_for_each_wire()},
            params{ps},
            circuit{bdl_circuit},
            sub_circuit{bdl_sub_circuit},
            sub_circuit_input_index{input_index_of_sub_circuit},
            circuit_with_sub_circuit{circuit.has_value() ?
                                         std::make_optional(make_circuit_with_sub_circuit(*circuit, *sub_circuit)) :
                                         std::nullopt}
    {
        static_assert(is_cell_level_layout_v<Lyt>, "Lyt is not a cell-level layout");
        static_assert(has_sidb_technology_v<Lyt>, "Lyt is not an SiDB layout");

        if constexpr (sim_bdl_wire_logic == simulate_bdl_wire_logic::COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS)
        {
            simulated_bdl_wires.emplace(std::vector<std::optional<charge_distribution_surface<Lyt>>>{});
            simulated_bdl_wires->reserve(num_inputs);
        }

        set_all_inputs();
    }
    /**
     * Dereference operator. Returns a reference to the layout with the current input state.
     *
     * @return Reference to the current layout.
     */
    [[nodiscard]] const Lyt& operator*() const noexcept
    {
        return layout;
    }
    /**
     * Prefix increment operator. Sets the next input state.
     *
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator++() noexcept
    {
        ++current_input_index;

        set_all_inputs();

        return *this;
    }
    /**
     * Postfix increment operator. Sets the next input state.
     *
     * @return Copy of `this` before incrementing.
     */
    bdl_input_iterator operator++(int) noexcept
    {
        auto result{*this};

        ++(*this);

        return result;
    }
    /**
     * Addition operator. Computes the input state of the current iterator plus the given integer.
     *
     * @param m The amount of input states to skip.
     * @return The input state of the current iterator plus the given integer.
     */
    [[nodiscard]] bdl_input_iterator operator+(const int m) const noexcept
    {
        auto result{*this};

        result += m;

        return result;
    }
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    /**
     * Addition assignment operator. Sets a next input state.
     *
     * @param m The amount of input states to skip.
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator+=(const int m) noexcept
    {
        current_input_index += m;

        set_all_inputs();

        return *this;
    }
#pragma GCC diagnostic pop
    /**
     * Subtraction operator. Computes the input state of the current iterator minus the given integer.
     *
     * @param m The amount of input states to skip.
     * @return The input state of the current iterator minus the given integer.
     */
    [[nodiscard]] bdl_input_iterator operator-(const int m) const noexcept
    {
        auto result{*this};

        result -= m;

        return result;
    }
    /**
     * Prefix decrement operator. Sets the previous input state.
     *
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator--() noexcept
    {
        --current_input_index;

        set_all_inputs();

        return *this;
    }
    /**
     * Postfix decrement operator. Sets the previous input state.
     *
     * @return Copy of `this` before decrementing.
     */
    bdl_input_iterator operator--(int) noexcept
    {
        auto result{*this};

        --(*this);

        return result;
    }
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    /**
     * Subtraction assignment operator. Sets a previous input state.
     *
     * @param m The amount of input states to skip.
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator-=(const int m) noexcept
    {
        current_input_index -= m;

        set_all_inputs();

        return *this;
    }
#pragma GCC diagnostic pop
    /**
     * Assignment operator. Sets the input state to the given integer.
     *
     * @param m The input state to set.
     */
    bdl_input_iterator& operator=(const uint64_t m) noexcept
    {
        current_input_index = m;

        set_all_inputs();

        return *this;
    }
    /**
     * Subscript operator. Computes the input state of the current iterator plus the given integer.
     *
     * @param m The amount of input states to skip.
     * @return The input state of the current iterator plus the given integer.
     */
    [[nodiscard]] bdl_input_iterator operator[](const int m) const noexcept
    {
        return (*this + m);
    }
    /**
     * Subtraction operator. Computes the difference between the current input index and the given iterator ones.
     *
     * @param other Iterator to compute the difference with.
     * @return The difference between the current input index and the given iterator ones.
     */
    [[nodiscard]] int64_t operator-(const bdl_input_iterator& other) const noexcept
    {
        return static_cast<int64_t>(current_input_index) - static_cast<int64_t>(other.current_input_index);
    }
    /**
     * Equality operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is equal to `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator==(const uint64_t m) const noexcept
    {
        return current_input_index == m;
    }
    /**
     * Inequality operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is not equal to `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator!=(const uint64_t m) const noexcept
    {
        return current_input_index != m;
    }
    /**
     * Less-than operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is less than `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator<(const uint64_t m) const noexcept
    {
        return current_input_index < m;
    }
    /**
     * Less-or-equal-than operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is less than or equal to `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator<=(const uint64_t m) const noexcept
    {
        return current_input_index <= m;
    }
    /**
     * Greater-than operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is greater than `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator>(const uint64_t m) const noexcept
    {
        return current_input_index > m;
    }
    /**
     * Greater-or-equal-than operator. Compares the current input index with the given integer.
     *
     * @param m Integer to compare with.
     * @return `true` if the current input index is greater than or equal to `m`, `false` otherwise.
     */
    [[nodiscard]] bool operator>=(const uint64_t m) const noexcept
    {
        return current_input_index >= m;
    }
    /**
     * Returns the total number of input BDL pairs of the given SiDB gate layout.
     *
     * @return The number of input BDL pairs.
     */
    [[nodiscard]] uint64_t num_input_pairs() const noexcept
    {
        return input_pairs.size();
    }
    /**
     * Returns the current input index.
     *
     * @return The current input index.
     */
    [[nodiscard]] uint64_t get_current_input_index() const noexcept
    {
        return current_input_index;
    }

    std::optional<charge_distribution_surface<Lyt>>
    get_expected_charge_distribution_with_sub_circuit_neutralized() noexcept
    {
        static_assert(sim_bdl_wire_logic == simulate_bdl_wire_logic::COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS,
                      "COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS must be enabled.");

        assert(simulated_bdl_wires.has_value() && "The simulated_bdl_wires container is not present.");
        assert(simulated_bdl_wires->size() >= current_input_index &&
               "The simulated_bdl_wires container is not synchronized with the current input index.");
        assert(sub_circuit.has_value() && "The sub_circuit container is not present.");

        std::optional<charge_distribution_surface<Lyt>>& maybe_cds = simulated_bdl_wires->at(current_input_index);

        if (!maybe_cds.has_value())
        {
            return std::nullopt;
        }

        sub_circuit->cell_layout.foreach_cell(
            [&](const auto& c)
            {
                if (const auto ct = sub_circuit->cell_layout.get_cell_type(c);
                            ct != sidb_technology::cell_type::OUTPUT_PERTURBER ||
                            circuit->skeleton.get_cell_type(c) ==
                                sidb_technology::cell_type::OUTPUT_PERTURBER)
                {
                    maybe_cds->assign_charge_state(c, sidb_charge_state::NEUTRAL, charge_index_mode::KEEP_CHARGE_INDEX);
                }
            });

        maybe_cds->update_after_charge_change(dependent_cell_mode::FIXED, energy_calculation::KEEP_OLD_ENERGY_VALUE);

        return maybe_cds;
    }

  private:
    /**
     * The layout to iterate over.
     */
    Lyt layout;
    /**
     * The detected input BDL pairs.
     */
    const std::vector<bdl_pair<cell<Lyt>>> input_pairs;
    /**
     * The amount of input BDL pairs.
     */
    const uint8_t num_inputs;
    /**
     * The detected input BDL wires.
     */
    const std::vector<bdl_wire<Lyt>> input_bdl_wires;
    /**
     * Last BDL pairs for each BDL wire.
     */
    const std::vector<bdl_pair<cell<Lyt>>> last_bdl_for_each_wire;
    /**
     * The current input index. There are \f$2^n\f$ possible input states for an \f$n\f$-input BDL layout.
     */
    uint64_t current_input_index{0ull};
    /**
     * Parameters for the BDL input iterator.
     */
    const bdl_input_iterator_params params;

    std::optional<std::vector<std::optional<charge_distribution_surface<Lyt>>>> simulated_bdl_wires{};

    std::optional<sidb_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>>            circuit{};
    std::optional<sidb_cell_level_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>> sub_circuit{};
    const std::optional<uint64_t>                                                 sub_circuit_input_index{};
    const std::optional<Lyt>                                                      circuit_with_sub_circuit{};

    /**
     * This function iterates through each wire in `input_bdl_wires`, identifies the first BDL pair
     * of type `INPUT`, and then finds the BDL pair within the same wire that has the maximum distance
     * from the starting pair. The resulting last BDL pairs are stored in `last_bdl_for_each_wire`.
     *
     * @note Assumes that `input_bdl_wires` and `last_bdl_for_each_wire` are accessible within the scope.
     */
    [[nodiscard]] std::vector<bdl_pair<cell<Lyt>>> determine_last_bdl_for_each_wire() noexcept
    {
        std::vector<bdl_pair<cell<Lyt>>> end_bdls{};
        end_bdls.reserve(input_bdl_wires.size());

        // Iterate through each wire in the input collection
        for (const auto& wire : input_bdl_wires)
        {
            // Find the first BDL pair in the wire with type INPUT
            auto start_bdl_it = std::find_if(wire.pairs.cbegin(), wire.pairs.cend(), [](const bdl_pair<cell<Lyt>>& bdl)
                                             { return bdl.type == sidb_technology::cell_type::INPUT; });

            // If no INPUT type BDL pair is found, skip this wire
            if (start_bdl_it == wire.pairs.cend())
            {
                continue;
            }

            const auto& start_bdl_pair = *start_bdl_it;

            // Find the BDL pair with the maximum distance from the start BDL pair
            const auto max_bdl_it =
                std::max_element(wire.pairs.cbegin(), wire.pairs.cend(),
                                 [&](const bdl_pair<cell<Lyt>>& a, const bdl_pair<cell<Lyt>>& b) -> bool
                                 {
                                     double distance_a = sidb_nm_distance(Lyt{}, start_bdl_pair.upper, a.upper);
                                     double distance_b = sidb_nm_distance(Lyt{}, start_bdl_pair.upper, b.upper);
                                     return distance_a < distance_b;
                                 });

            // If a valid BDL pair is found, add it to the end BDLs collection
            if (max_bdl_it != wire.pairs.cend())
            {
                end_bdls.emplace_back(*max_bdl_it);
            }
        }

        return end_bdls;
    }
    /**
     * Sets all input cells of the layout according to the current input index. The input index is interpreted as a
     * binary number, where the \f$i\f$-th bit represents the input state of the \f$i\f$-th input BDL pair. If the bit
     * is `1`, the lower BDL dot is set and the upper BDL dot removed. If the bit is `0`, the upper BDL dot is removed
     * and the lower BDL dot set.
     */
    void set_all_inputs() noexcept
    {
        assert(num_inputs == input_bdl_wires.size() && "number of inputs and number of wires don't match");

        for (uint64_t i = num_inputs - 1; i < num_inputs; --i)
        {
            const auto& input_i = input_pairs[i];

            if ((current_input_index & (uint64_t{1ull} << (num_inputs - 1 - i))) != 0ull)
            {
                const auto distance_between_end_bdl_and_upper_input =
                    sidb_nm_distance(Lyt{}, input_i.upper, last_bdl_for_each_wire[i].upper);
                const auto distance_between_end_bdl_and_lower_input =
                    sidb_nm_distance(Lyt{}, input_i.lower, last_bdl_for_each_wire[i].upper);

                if (distance_between_end_bdl_and_upper_input < distance_between_end_bdl_and_lower_input)
                {
                    layout.assign_cell_type(input_i.lower, technology<Lyt>::cell_type::EMPTY);
                    layout.assign_cell_type(input_i.upper, technology<Lyt>::cell_type::INPUT);
                }

                else
                {
                    layout.assign_cell_type(input_i.lower, technology<Lyt>::cell_type::INPUT);
                    layout.assign_cell_type(input_i.upper, technology<Lyt>::cell_type::EMPTY);
                }
            }
            else
            {
                if (params.input_bdl_config ==
                    bdl_input_iterator_params::input_bdl_configuration::PERTURBER_DISTANCE_ENCODED)
                {
                    const auto distance_between_end_bdl_and_upper_input =
                        sidb_nm_distance(Lyt{}, input_i.upper, last_bdl_for_each_wire[i].upper);
                    const auto distance_between_end_bdl_and_lower_input =
                        sidb_nm_distance(Lyt{}, input_i.lower, last_bdl_for_each_wire[i].upper);

                    if (distance_between_end_bdl_and_upper_input < distance_between_end_bdl_and_lower_input)
                    {
                        layout.assign_cell_type(input_i.lower, technology<Lyt>::cell_type::INPUT);
                        layout.assign_cell_type(input_i.upper, technology<Lyt>::cell_type::EMPTY);
                    }

                    else
                    {
                        layout.assign_cell_type(input_i.lower, technology<Lyt>::cell_type::EMPTY);
                        layout.assign_cell_type(input_i.upper, technology<Lyt>::cell_type::INPUT);
                    }
                }
                else
                {
                    // set input i to 0
                    layout.assign_cell_type(input_i.upper, technology<Lyt>::cell_type::EMPTY);
                    layout.assign_cell_type(input_i.lower, technology<Lyt>::cell_type::EMPTY);
                }
            }
        }

        if constexpr (sim_bdl_wire_logic == simulate_bdl_wire_logic::COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS)
        {
            simulate_bdl_wires_in_circuit();
        }
    }

    void simulate_bdl_wires_in_circuit() noexcept
    {
        static_assert(sim_bdl_wire_logic == simulate_bdl_wire_logic::COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS,
                      "COLLECT_EXPECTED_CHARGE_DISTRIBUTIONS must be enabled.");

        assert(simulated_bdl_wires.has_value() && "The simulated_bdl_wires container is not present.");
        assert(simulated_bdl_wires->size() >= current_input_index &&
               "The simulated_bdl_wires container is not synchronized with the current input index.");
        assert(circuit.has_value() && "The circuit container is not present.");
        assert(sub_circuit.has_value() && "The sub_circuit container is not present.");
        assert(sub_circuit_input_index.has_value() && "The input index of the sub-circuit must be present.");
        assert(circuit_with_sub_circuit.has_value() && "The circuit with sub circuit must be present.");

        if (simulated_bdl_wires->size() == current_input_index)
        {
            simulated_bdl_wires->emplace_back();
        }

        charge_distribution_surface<Lyt> current_cds = charge_distribution_surface<Lyt>{*circuit_with_sub_circuit};
        current_cds.assign_all_charge_states(sidb_charge_state::NEGATIVE, charge_index_mode::KEEP_CHARGE_INDEX);

        const auto assign_logic_state_to_bdl_pairs =
            [&](const typename std::vector<bdl_pair<cell<Lyt>>>::const_iterator begin,
                const typename std::vector<bdl_pair<cell<Lyt>>>::const_iterator end, const bool signal) noexcept
        {
            for (auto it = begin; it != end; ++it)

            {
                assert(it->type != sidb_technology::cell_type::INPUT && "input BDL pairs are handled separately");

                current_cds.assign_charge_state(signal ? it->upper : it->lower, sidb_charge_state::NEUTRAL,
                                                charge_index_mode::KEEP_CHARGE_INDEX);
            }
        };

        std::unordered_map<tile<GateLyt>, std::unordered_map<tile<GateLyt>, bool>> expected_signal_at_gate_connection{};

        uint64_t current_input_number             = 0;
        uint64_t current_sub_circuit_input_number = 0;

        const auto is_bit_set = [&](const uint64_t input_index, uint64_t& input_number, const uint64_t number_of_inputs)
        { return (input_index & (uint64_t{1ull} << (number_of_inputs - 1 - input_number++))) != 0ull; };

        for (uint64_t wire_ix = 0; wire_ix < circuit->bdl_wires.size(); ++wire_ix)
        {
            const bdl_wire<Lyt>& wire = circuit->bdl_wires.at(wire_ix);

            assert((wire.port.dir == port_direction::SOUTH || wire.port.dir == port_direction::EAST ||
                    wire.port.dir == port_direction::NONE) &&
                   "Wrong port direction; only row clocking is supported");

            const auto& [upper_tile, lower_tile] = circuit->gate_connections.at(wire_ix);

            typename std::vector<bdl_pair<cell<Lyt>>>::const_iterator assign_logic_state_to_bdl_pairs_start_it =
                wire.pairs.cbegin();

            // if (circuit->gate_layout.is_pi_tile(upper_tile)) todo
            if (wire.pairs.front().type == sidb_technology::cell_type::INPUT)
            {
                // assert((expected_signal_at_gate_connection.count(lower_tile) == 0 ||
                //         expected_signal_at_gate_connection.at(lower_tile).count(upper_tile) == 0) &&
                //        "PI is visited twice"); todo

                const bool current_bit_set = is_bit_set(current_input_index, current_input_number, num_inputs);

                expected_signal_at_gate_connection[lower_tile].insert({upper_tile, current_bit_set});

                const bdl_pair<cell<Lyt>>& input_pair = wire.pairs.front();

                assert(input_pair.type == sidb_technology::cell_type::INPUT &&
                       "BDL wire connecting to a PI does not start with an input BDL pair");

                current_cds.assign_charge_state(current_bit_set ? input_pair.upper : input_pair.lower,
                                                sidb_charge_state::NEUTRAL, charge_index_mode::KEEP_CHARGE_INDEX);

                assign_logic_state_to_bdl_pairs_start_it = std::next(wire.pairs.cbegin(), 1);
            }

            // assert(expected_signal_at_gate_connection.count(lower_tile) != 0 &&
            //        expected_signal_at_gate_connection.at(lower_tile).count(upper_tile) != 0 &&
            //        "Tile is visited before the incoming tile that connects it"); todo

            const bool expected_signal_for_wire = expected_signal_at_gate_connection.at(lower_tile).at(upper_tile);

            if (current_sub_circuit_input_number < sub_circuit->circuit.num_inputs &&
                wire.pairs.front().upper ==
                    sub_circuit->circuit.input_bdl_pairs.at(current_sub_circuit_input_number).upper)
            {
                const bool bitset = is_bit_set(*sub_circuit_input_index, current_sub_circuit_input_number,
                                                           sub_circuit->circuit.num_inputs);
                if (expected_signal_for_wire != bitset)
                {
                    // input mismatches with circuit

                    return;
                }
            }

            assign_logic_state_to_bdl_pairs(assign_logic_state_to_bdl_pairs_start_it, wire.pairs.cend(),
                                            expected_signal_for_wire);

            const uint32_t num_inputs_to_lower_tile =
                circuit->gate_layout.node_function(circuit->gate_layout.get_node(lower_tile)).num_vars();

            assert(expected_signal_at_gate_connection.at(lower_tile).size() <= num_inputs_to_lower_tile &&
                   "Number of tiles visited connecting to the current tile exceeds the number of inputs to the node "
                   "function");

            if (circuit->gate_layout.is_po_tile(lower_tile) ||
                expected_signal_at_gate_connection.at(lower_tile).size() < num_inputs_to_lower_tile)
            {
                continue;
            }

            const std::vector<tile<GateLyt>>& outgoing_tiles = circuit->gate_layout.outgoing_data_flow(lower_tile);

            assert(!outgoing_tiles.empty() && "Non-PO tile does not have outgoing data flow");

            if constexpr (has_is_fanout_v<GateLyt>)
            {
                if (circuit->gate_layout.is_fanout(circuit->gate_layout.get_node(lower_tile)))
                {
                    for (const tile<GateLyt>& lower_lower_t : outgoing_tiles)
                    {
                        expected_signal_at_gate_connection[lower_lower_t].insert(
                            {lower_tile, expected_signal_for_wire});
                    }

                    continue;
                }
            }

            assert(outgoing_tiles.size() == 1 && "Tile with single-output gate has more than one outgoing tile.");

            const tile<GateLyt>& first_input_tile = expected_signal_at_gate_connection.at(lower_tile).cbegin()->first;

            assert((num_inputs_to_lower_tile == 1 ||
                    (expected_signal_at_gate_connection.at(lower_tile).size() == 2 &&
                     first_input_tile.y ==
                         std::next(expected_signal_at_gate_connection.at(lower_tile).cbegin(), 1)->first.y &&
                     first_input_tile.x !=
                         std::next(expected_signal_at_gate_connection.at(lower_tile).cbegin(), 1)->first.x)) &&
                   "Only row clocking is supported; inputs to a tile must be on the same y with differing x");

            auto tt_inp = static_cast<uint8_t>(expected_signal_at_gate_connection.at(lower_tile).at(first_input_tile));

            if (num_inputs_to_lower_tile == 2)
            {
                const tile<GateLyt>& second_input_tile =
                    std::next(expected_signal_at_gate_connection.at(lower_tile).cbegin(), 1)->first;
                const auto tt_inp_second =
                    static_cast<uint8_t>(expected_signal_at_gate_connection.at(lower_tile).at(second_input_tile));

                // tt_inp <- 2 * L_in + R_in
                if (first_input_tile.x < second_input_tile.x)
                {
                    tt_inp = 2 * tt_inp + tt_inp_second;
                }
                else
                {
                    tt_inp += 2 * tt_inp_second;
                }
            }

            expected_signal_at_gate_connection[outgoing_tiles.front()].insert(
                {lower_tile,
                 kitty::get_bit(circuit->gate_layout.node_function(circuit->gate_layout.get_node(lower_tile)),
                                tt_inp)});
        }

        // the charge index is not updated

        (*simulated_bdl_wires)[current_input_index].emplace(std::move(current_cds));
    }

    [[nodiscard]] static Lyt make_circuit_with_sub_circuit(
        const sidb_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>&            circuit,
        const sidb_cell_level_bdl_circuit<Lyt, GateLyt, SkeletonGateLibrary>& sub_circuit) noexcept
    {
        Lyt circuit_with_sub_circuit = circuit.skeleton.clone();

        sub_circuit.cell_layout.foreach_cell(
            [&](const cell<Lyt>& cell)
            { circuit_with_sub_circuit.assign_cell_type(cell, sidb_technology::cell_type::NORMAL); });

        return circuit_with_sub_circuit;
    }
};

}  // namespace fiction

// make `bdl_input_iterator` compatible with STL iterator categories
namespace std
{
template <typename Lyt>
struct iterator_traits<fiction::bdl_input_iterator<Lyt>>
{
    using iterator_category = std::random_access_iterator_tag;
    using difference_type   = int64_t;
    using value_type        = Lyt;
};
}  // namespace std

#endif  // FICTION_BDL_INPUT_ITERATOR_HPP
